version: '3'
services:
  connector-rss-enhancer:
    build:
      context: ./connectors/rss-report-enhancer
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=CHANGE_ME
      - CONNECTOR_ID=CHANGE_ME
      # 基本設定
      - CONNECTOR_NAME=RSS Report Enhancer
      - CONNECTOR_SCOPE=Report
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      # 実行間隔（秒）
      - WAIT_TIME=60
      
      # レポート処理設定
      # 処理対象レポートタイプ（カンマ区切りのリスト）
      - TARGET_REPORT_TYPES=rss-report #external-import,threat-report,rss-feed,rss,rss-report
      # すべてのレポートを処理するかのフラグ（true/false）
      - PROCESS_ALL_REPORTS=false
      # 処理済みレポートを識別するラベル名
      - PROCESSED_LABEL=rss-enhanced
      # ラベルの色（16進数カラーコード）
      - PROCESSED_LABEL_COLOR=#ff9900
      
      # デバッグ設定
      - DEBUG_MODE=false
      
      # PDF生成オプション
      # レイアウト保持設定
      - PRESERVE_ORIGINAL_LAYOUT=true
      # 画像関連設定
      - INCLUDE_IMAGES_IN_PDF=true
      - PDF_IMAGE_QUALITY=85
      - MAX_IMAGES_IN_PDF=20
      # 広告除去戦略 ("extract", "minimal", "auto")
      # extract: コンテンツのみを抽出して新しいHTML生成
      # minimal: 基本的な広告のみ除去し、レイアウト保持
      # auto: HTMLの複雑さに基づいて自動選択
      - AD_REMOVAL_STRATEGY=auto

      # 起動時の全レポート処理設定
      - PROCESS_ALL_ON_START=false
      # 起動時処理の最大レポート数（0=無制限）
      - MAX_REPORTS_ON_START=100
    restart: always
    depends_on:
      - opencti
    mem_limit: 1g
    shm_size: '2gb'